config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

 # root '/login', to: 'sessions#new'

  get 'pronosticos/new/:id' => 'pronosticos#new'
  
  get 'usuarios/:id/pronosticos/:jornada' => 'pronosticos#cargar'

  get 'resultados/new/:id' => 'resultados#new'

  get 'resultados/:id' => 'resultados#show'

  get 'usuarios/:id' => 'usuarios#show'

  #get    '/signup',  to: 'usuarios#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  #get 'usuarios/' => 'usuarios#index'

  resources :pronosticos
  resources :resultados
	resources :home
  #resources :juegos
end

app/controllers/pronosticos_controller.rb
class PronosticosController < ApplicationController

	def cargar
		@usuario = Usuario.find(params[:id])
		@j = Juego.where(jornada: params[:jornada]).first
		@juegos = Juego.where(jornada: params[:jornada])
		ya =UsuarioPartido.exists?(juego_id: @j.juego_id, usuario_id: params[:id])
		if(ya==true)
			@pronosticos = true
			@partidos = Array.new()
			@juegos.each do |jp|
				@partidos.push(jp.juego_id)	
			end
			@resultados = UsuarioPartido.where(juego_id: @partidos,usuario_id: params[:id])
		end
	end


    def index


    	@puntosPorUsuario = Hash.new 
    	@totalMarcadoresExactos = 0;
    	
    	#Arrays
    	@ArrayMarcadoresExactos = Array.new()
    	@tablaPosiciones = Array.new()
    	@usuarios = Usuario.all()
    	 @juegos = Juego.where(registrado: 1)
    	 @usuarios.each do |usuario|
    	 	 @totalPuntos= 0
    	 	 @totalMarcadoresExactos = 0
    	 	 @juegos.each do |juego|
    	 	 	 UsuarioPartido.where(usuario_id: usuario.id, juego_id: juego.id).each do |us|
    	 	 	  if(juego.goles_local.to_s == us.goles_local.to_s && juego.goles_visitante.to_s == us.goles_visitante.to_s)
                  	@totalPuntos= @totalPuntos.to_i +  2
                  	@totalMarcadoresExactos = @totalMarcadoresExactos + 1
                  elsif obtener_resultado_juego(juego.goles_local.to_s, juego.goles_visitante.to_s) == obtener_resultado_juego(us.goles_local.to_s,us.goles_visitante.to_s)
                    @totalPuntos= @totalPuntos.to_i + 1
                  else
                   @totalPuntos= @totalPuntos.to_i +  0
                 end
             end
    	 	 end
    	 	 @puntosPorUsuario[usuario.nombre] = @totalPuntos.to_i
    	 	  @ArrayMarcadoresExactos[usuario.id] = @totalMarcadoresExactos.to_i
    	 	  @tablaPosiciones.push([usuario.nombre, @totalPuntos.to_i,@totalMarcadoresExactos.to_i])
    	 	  
    	  end
    	 @puntosPorUsuario = Hash[@puntosPorUsuario.sort_by{|k,v| v}.reverse.to_h]
    	 
    	 
    	@tablaPosiciones =  @tablaPosiciones.sort_by{ |i,j,k| [j,k,i]}.reverse

    end
	
  def new
      @juegos = Juego.find([63,64])
  end
  
 def obtener_resultado_juego(goles_local,goles_visitante)
    if(goles_local.to_i==goles_visitante.to_i)
      return "empate"
    elsif (goles_local.to_i > goles_visitante.to_i)
      return "gano_local"
    else
      return "gano_visitante"
    end
  end


  def create
      
      @juegos = Juego.where(jornada: params[:jornada])

      @juegos.each  do |j|
        @pronostico = UsuarioPartido.new()
        @pronostico.usuario_id = params[:usuario_id]
        @pronostico.juego_id = j.juego_id
        @pronostico.goles_local = params["goles_local_#{j.juego_id}"]
        @pronostico.goles_visitante = params["goles_visitante_#{j.juego_id}"]
        @pronostico.save
      end

      @usuario = Usuario.find(params[:usuario_id])
      @usuario.registro = 1
      @usuario.save

      redirect_to "/pronosticos"
  end

  def get_puntos_por_partido(usuario_id)
    @juego = Juego.find(params[:id])
      if(@juego.goles_local != "" && @juego.goles_visitante != "")
            UsuarioPartido.where(usuario_id: usuario_id, juego_id: @juego.id).each do |us|
                if(@juego.goles_local.to_s == us.goles_local.to_s && @juego.goles_visitante.to_s == us.goles_visitante.to_s)
                  return 2
                elsif obtener_resultado_juego(@juego.goles_local.to_s, @juego.goles_visitante.to_s) == obtener_resultado_juego(us.goles_local.to_s,us.goles_visitante.to_s)
                  return 1
                else
                  return 0
                end
            end

      else
        return ""
      end
  end
  helper_method :get_puntos_por_partido
  
end

app/helpers/pronosticos_helper.rb
module PronosticosHelper
end

app/views/pronosticos/cargar.html.erb
<%if @pronosticos == true %>

<table class="table">
<tr>
  <td>Usuario</td>
        <td><%= @usuario.nombre %></td>
       
        
    </tr>
</table>
<table class="table">
  <tr>


  <td>Pronostico</td>
  <td>Puntos</td>
    </tr>
         
	
        <%@resultados.each do |us| %>
	<tr>
        <%@juego = Juego.where(juego_id: us.juego_id).take%>
	<td><%= @juego.local%> <%=  us.goles_local %> - <%=@juego.visitante%> <%=  us.goles_visitante %></td>
	<td></td>
     	</tr>   
        <% end %>
        
     
    
</table>

<%else%>

	<%= form_tag pronosticos_path do %>

	<table class="table">
  	<thead>
    	<tr>
      	<th>Local</th>
      	<th></th>
      	<th></th>
      	<th>Visitante</th>

    	</tr>
 	 </thead>
  	<tbody>
	 <% @juegos.each do |juego| %>
        <tr>
          <td><%= juego.local %></td>
          <td><input id="goles_locales" name="goles_local_<%=juego.juego_id%>" type="text" /></td>
          	<td><input id="goles_visitantes" name="goles_visitante_<%=juego.juego_id%>" type="text" /></td>
          	<td><%= juego.visitante %></td>
        	</tr>
	<% end %>
    	</tbody>
  	</table>


	<input type="hidden" id="usuario_id" name="usuario_id" value="<%=params[:id]%>  ">
	<input type="hidden" id="jornada" name="jornada" value="<%=params[:jornada]%>"> 
  	<%= submit_tag %>
	<% end %>

<% end %>

app/views/pronosticos/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Puntos</th>
      <th>Marcadores Exactos</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @tablaPosiciones.each  do |i,j,k| %>
        <tr>
        <%Usuario.where(nombre: i).each do |us| %>
 
          <td><a href="/usuarios/<%= us.id %>"><%=i  %></a></td>
         
          <td><%=j  %></td>
           <td><%=k  %></td>
            <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/pronosticos/new.html.erb
<%= form_tag pronosticos_path do %>

<table class="table">
  <thead>
    <tr>
      <th>Local</th>
      <th></th>
      <th></th>
      <th>Visitante</th>

    </tr>
  </thead>
  <tbody>
      <% @juegos.each do |juego| %>
        <tr>
          <td><%= juego.local %></td>
          <td><input id="goles_locales" name="goles_local_<%=juego.juego_id%>" type="text" /></td>
          <td><input id="goles_visitantes" name="goles_visitante_<%=juego.juego_id%>" type="text" /></td>
          <td><%= juego.visitante %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<input type="hidden" id="usuario_id" name="usuario_id" value="<%=params[:id]%>  ">
  <%= submit_tag %>
<% end %>