config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

 # root '/login', to: 'sessions#new'

  get 'pronosticos/new/:id' => 'pronosticos#new'
  
  get 'usuarios/:id/pronosticos/:jornada' => 'pronosticos#cargar'

  get 'resultados/new/:id' => 'resultados#new'

  get 'resultados/:id' => 'resultados#show'

  get 'usuarios/:id' => 'usuarios#show'

  #get    '/signup',  to: 'usuarios#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  #get 'usuarios/' => 'usuarios#index'

  resources :pronosticos
  resources :resultados
	resources :home
  #resources :juegos
end

app/controllers/resultados_controller.rb
class ResultadosController < ApplicationController

  def index
    @juegos = Juego.all()
  end

    def new
    @juego = Juego.find(params[:id])

  end
  
  def show
    @juego = Juego.where(juego_id: params[:id]).take
    @usuarios = Usuario.all()
#@usuarios = Usuario.find(2)		 
 end
  
   def create
   	  @juego = Juego.find(params[:juego_id])
      @juego.goles_local = params[:goles_local]
      @juego.goles_visitante = params[:goles_visitante]
      @juego.registrado = 1
      @juego.save
      redirect_to "/resultados"
   end

  def obtener_resultado_juego(goles_local,goles_visitante)
    if(goles_local.to_i==goles_visitante.to_i)
      return "empate"
    elsif (goles_local.to_i > goles_visitante.to_i)
      return "gano_local"
    else
      return "gano_visitante"
    end
  end
  helper_method :obtener_resultado_juego



  def get_puntos_por_partido(usuario_id)
    @juego = Juego.find(params[:id])
      if(@juego.goles_local != "" && @juego.goles_visitante != "")
            UsuarioPartido.where(usuario_id: usuario_id, juego_id: @juego.id).each do |us|
                if(@juego.goles_local.to_s == us.goles_local.to_s && @juego.goles_visitante.to_s == us.goles_visitante.to_s)
                  return 2
                elsif obtener_resultado_juego(@juego.goles_local.to_s, @juego.goles_visitante.to_s) == obtener_resultado_juego(us.goles_local.to_s,us.goles_visitante.to_s)
                  return 1
                else
                  return 0
                end
            end

      else
        return ""
      end
  end
  helper_method :get_puntos_por_partido

end

app/helpers/resultados_helper.rb
module ResultadosHelper
end

app/views/resultados/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Local</th>
      <th></th>
      <th>Visitante</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @juegos.each do |juego| %>
        <tr>
          <td><%= juego.local  %></td>
          <td><%= juego.goles_local%></td>
          <td><%= juego.visitante%></td>
           <td><%= juego.goles_visitante%></td>
          <td><a href="/resultados/<%= juego.juego_id %>">Ver detalle</a></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/resultados/new.html.erb

<%if @juego.registrado == 1 %>
    <p>
        <b>Local:</b><%= @juego.local %> </b><%= @juego.goles_local %>
    </p>
    <p>
        <b>Visitante:</b><%= @juego.visitante %><%= @juego.goles_visitante %>
    </p>

<%else %>
<%= form_tag resultados_path do %>

    <p>
        <b>Local:</b><%= @juego.local %> </b>
        <td><input id="goles_locales" name="goles_local" type="text" /></td>
          
    </p>
    <p>
        <b>Visitante:</b><%= @juego.visitante %>
              <td><input id="goles_visitantes" name="goles_visitante" type="text" /></td>
   
    </p>
    
    
    <input type="hidden" id="juego_id" name="juego_id" value="<%=params[:id]%>  ">
  <%= submit_tag %>
<% end %>

<%end %>

app/views/resultados/show.html.erb
<body>
<table class="table">
<tr>
        <td><%= @juego.local %> </td><td><%= @juego.goles_local %>-<%= @juego.goles_visitante %></td><td><%= @juego.visitante %></td>
        
    </tr>
</table>
<table class="table">
  <tr>
  <td>Usuario</td>
  <td>Pronostico</td>
  <td>Puntos</td>
    </tr>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>

        <%UsuarioPartido.where(usuario_id: usuario.id, juego_id: @juego.juego_id).each do |us| %>
        <td><%= us.goles_local %> - <%= us.goles_visitante %></td>
        <td></td>
        <% end %>
          <td><%=%></td>
      </tr>
      <% end %>
</table>
</body>